// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: cursor_metrics

#ifndef UI_SCREEN_H
#define UI_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen
extern void ui_Screen_screen_init(void);
extern void ui_Screen_screen_destroy(void);
extern lv_obj_t *ui_Screen;
extern lv_obj_t *ui_includedTitleLabel;
extern lv_obj_t *ui_includedUsageBar;
extern lv_obj_t *ui_includedAmountLabel;
extern lv_obj_t *ui_includedCycleLabel;
extern lv_obj_t *ui_paidTitleLabel;
extern lv_obj_t *ui_paidUsageBar;
extern lv_obj_t *ui_paidAmountLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

