[env:esp32-c6-lcd-147]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
platform_packages =
  tool-esptoolpy @ platformio/tool-esptoolpy
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.partitions = default.csv

lib_deps =
  lvgl/lvgl@8.3.11
  moononournation/GFX Library for Arduino@1.5.9

build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -I include
  -D CORE_DEBUG_LEVEL=3

lib_ldf_mode = deep+
